openapi: 3.0.0
info:
  title: vocab-admin
  version: '1.0'
  description: Admin apis that manage the public dictionaries.
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      description: ''
